// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/tmavrin/igp-code-challenge/internal/store"
	"github.com/tmavrin/igp-code-challenge/internal/types"
)

type PersistentStoreProvider struct {
	AccountCreateStub        func(context.Context, types.AuthCredentials) (types.Account, error)
	accountCreateMutex       sync.RWMutex
	accountCreateArgsForCall []struct {
		arg1 context.Context
		arg2 types.AuthCredentials
	}
	accountCreateReturns struct {
		result1 types.Account
		result2 error
	}
	accountCreateReturnsOnCall map[int]struct {
		result1 types.Account
		result2 error
	}
	AccountGetByStub        func(context.Context, types.AccountFilter) (types.Account, error)
	accountGetByMutex       sync.RWMutex
	accountGetByArgsForCall []struct {
		arg1 context.Context
		arg2 types.AccountFilter
	}
	accountGetByReturns struct {
		result1 types.Account
		result2 error
	}
	accountGetByReturnsOnCall map[int]struct {
		result1 types.Account
		result2 error
	}
	CommitTxStub        func(context.Context) error
	commitTxMutex       sync.RWMutex
	commitTxArgsForCall []struct {
		arg1 context.Context
	}
	commitTxReturns struct {
		result1 error
	}
	commitTxReturnsOnCall map[int]struct {
		result1 error
	}
	RollbackTxStub        func(context.Context) error
	rollbackTxMutex       sync.RWMutex
	rollbackTxArgsForCall []struct {
		arg1 context.Context
	}
	rollbackTxReturns struct {
		result1 error
	}
	rollbackTxReturnsOnCall map[int]struct {
		result1 error
	}
	WithTxStub        func(context.Context) (store.Persistent, error)
	withTxMutex       sync.RWMutex
	withTxArgsForCall []struct {
		arg1 context.Context
	}
	withTxReturns struct {
		result1 store.Persistent
		result2 error
	}
	withTxReturnsOnCall map[int]struct {
		result1 store.Persistent
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PersistentStoreProvider) AccountCreate(arg1 context.Context, arg2 types.AuthCredentials) (types.Account, error) {
	fake.accountCreateMutex.Lock()
	ret, specificReturn := fake.accountCreateReturnsOnCall[len(fake.accountCreateArgsForCall)]
	fake.accountCreateArgsForCall = append(fake.accountCreateArgsForCall, struct {
		arg1 context.Context
		arg2 types.AuthCredentials
	}{arg1, arg2})
	stub := fake.AccountCreateStub
	fakeReturns := fake.accountCreateReturns
	fake.recordInvocation("AccountCreate", []interface{}{arg1, arg2})
	fake.accountCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PersistentStoreProvider) AccountCreateCallCount() int {
	fake.accountCreateMutex.RLock()
	defer fake.accountCreateMutex.RUnlock()
	return len(fake.accountCreateArgsForCall)
}

func (fake *PersistentStoreProvider) AccountCreateCalls(stub func(context.Context, types.AuthCredentials) (types.Account, error)) {
	fake.accountCreateMutex.Lock()
	defer fake.accountCreateMutex.Unlock()
	fake.AccountCreateStub = stub
}

func (fake *PersistentStoreProvider) AccountCreateArgsForCall(i int) (context.Context, types.AuthCredentials) {
	fake.accountCreateMutex.RLock()
	defer fake.accountCreateMutex.RUnlock()
	argsForCall := fake.accountCreateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PersistentStoreProvider) AccountCreateReturns(result1 types.Account, result2 error) {
	fake.accountCreateMutex.Lock()
	defer fake.accountCreateMutex.Unlock()
	fake.AccountCreateStub = nil
	fake.accountCreateReturns = struct {
		result1 types.Account
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) AccountCreateReturnsOnCall(i int, result1 types.Account, result2 error) {
	fake.accountCreateMutex.Lock()
	defer fake.accountCreateMutex.Unlock()
	fake.AccountCreateStub = nil
	if fake.accountCreateReturnsOnCall == nil {
		fake.accountCreateReturnsOnCall = make(map[int]struct {
			result1 types.Account
			result2 error
		})
	}
	fake.accountCreateReturnsOnCall[i] = struct {
		result1 types.Account
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) AccountGetBy(arg1 context.Context, arg2 types.AccountFilter) (types.Account, error) {
	fake.accountGetByMutex.Lock()
	ret, specificReturn := fake.accountGetByReturnsOnCall[len(fake.accountGetByArgsForCall)]
	fake.accountGetByArgsForCall = append(fake.accountGetByArgsForCall, struct {
		arg1 context.Context
		arg2 types.AccountFilter
	}{arg1, arg2})
	stub := fake.AccountGetByStub
	fakeReturns := fake.accountGetByReturns
	fake.recordInvocation("AccountGetBy", []interface{}{arg1, arg2})
	fake.accountGetByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PersistentStoreProvider) AccountGetByCallCount() int {
	fake.accountGetByMutex.RLock()
	defer fake.accountGetByMutex.RUnlock()
	return len(fake.accountGetByArgsForCall)
}

func (fake *PersistentStoreProvider) AccountGetByCalls(stub func(context.Context, types.AccountFilter) (types.Account, error)) {
	fake.accountGetByMutex.Lock()
	defer fake.accountGetByMutex.Unlock()
	fake.AccountGetByStub = stub
}

func (fake *PersistentStoreProvider) AccountGetByArgsForCall(i int) (context.Context, types.AccountFilter) {
	fake.accountGetByMutex.RLock()
	defer fake.accountGetByMutex.RUnlock()
	argsForCall := fake.accountGetByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PersistentStoreProvider) AccountGetByReturns(result1 types.Account, result2 error) {
	fake.accountGetByMutex.Lock()
	defer fake.accountGetByMutex.Unlock()
	fake.AccountGetByStub = nil
	fake.accountGetByReturns = struct {
		result1 types.Account
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) AccountGetByReturnsOnCall(i int, result1 types.Account, result2 error) {
	fake.accountGetByMutex.Lock()
	defer fake.accountGetByMutex.Unlock()
	fake.AccountGetByStub = nil
	if fake.accountGetByReturnsOnCall == nil {
		fake.accountGetByReturnsOnCall = make(map[int]struct {
			result1 types.Account
			result2 error
		})
	}
	fake.accountGetByReturnsOnCall[i] = struct {
		result1 types.Account
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) CommitTx(arg1 context.Context) error {
	fake.commitTxMutex.Lock()
	ret, specificReturn := fake.commitTxReturnsOnCall[len(fake.commitTxArgsForCall)]
	fake.commitTxArgsForCall = append(fake.commitTxArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CommitTxStub
	fakeReturns := fake.commitTxReturns
	fake.recordInvocation("CommitTx", []interface{}{arg1})
	fake.commitTxMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PersistentStoreProvider) CommitTxCallCount() int {
	fake.commitTxMutex.RLock()
	defer fake.commitTxMutex.RUnlock()
	return len(fake.commitTxArgsForCall)
}

func (fake *PersistentStoreProvider) CommitTxCalls(stub func(context.Context) error) {
	fake.commitTxMutex.Lock()
	defer fake.commitTxMutex.Unlock()
	fake.CommitTxStub = stub
}

func (fake *PersistentStoreProvider) CommitTxArgsForCall(i int) context.Context {
	fake.commitTxMutex.RLock()
	defer fake.commitTxMutex.RUnlock()
	argsForCall := fake.commitTxArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PersistentStoreProvider) CommitTxReturns(result1 error) {
	fake.commitTxMutex.Lock()
	defer fake.commitTxMutex.Unlock()
	fake.CommitTxStub = nil
	fake.commitTxReturns = struct {
		result1 error
	}{result1}
}

func (fake *PersistentStoreProvider) CommitTxReturnsOnCall(i int, result1 error) {
	fake.commitTxMutex.Lock()
	defer fake.commitTxMutex.Unlock()
	fake.CommitTxStub = nil
	if fake.commitTxReturnsOnCall == nil {
		fake.commitTxReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitTxReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PersistentStoreProvider) RollbackTx(arg1 context.Context) error {
	fake.rollbackTxMutex.Lock()
	ret, specificReturn := fake.rollbackTxReturnsOnCall[len(fake.rollbackTxArgsForCall)]
	fake.rollbackTxArgsForCall = append(fake.rollbackTxArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RollbackTxStub
	fakeReturns := fake.rollbackTxReturns
	fake.recordInvocation("RollbackTx", []interface{}{arg1})
	fake.rollbackTxMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PersistentStoreProvider) RollbackTxCallCount() int {
	fake.rollbackTxMutex.RLock()
	defer fake.rollbackTxMutex.RUnlock()
	return len(fake.rollbackTxArgsForCall)
}

func (fake *PersistentStoreProvider) RollbackTxCalls(stub func(context.Context) error) {
	fake.rollbackTxMutex.Lock()
	defer fake.rollbackTxMutex.Unlock()
	fake.RollbackTxStub = stub
}

func (fake *PersistentStoreProvider) RollbackTxArgsForCall(i int) context.Context {
	fake.rollbackTxMutex.RLock()
	defer fake.rollbackTxMutex.RUnlock()
	argsForCall := fake.rollbackTxArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PersistentStoreProvider) RollbackTxReturns(result1 error) {
	fake.rollbackTxMutex.Lock()
	defer fake.rollbackTxMutex.Unlock()
	fake.RollbackTxStub = nil
	fake.rollbackTxReturns = struct {
		result1 error
	}{result1}
}

func (fake *PersistentStoreProvider) RollbackTxReturnsOnCall(i int, result1 error) {
	fake.rollbackTxMutex.Lock()
	defer fake.rollbackTxMutex.Unlock()
	fake.RollbackTxStub = nil
	if fake.rollbackTxReturnsOnCall == nil {
		fake.rollbackTxReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rollbackTxReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PersistentStoreProvider) WithTx(arg1 context.Context) (store.Persistent, error) {
	fake.withTxMutex.Lock()
	ret, specificReturn := fake.withTxReturnsOnCall[len(fake.withTxArgsForCall)]
	fake.withTxArgsForCall = append(fake.withTxArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.WithTxStub
	fakeReturns := fake.withTxReturns
	fake.recordInvocation("WithTx", []interface{}{arg1})
	fake.withTxMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PersistentStoreProvider) WithTxCallCount() int {
	fake.withTxMutex.RLock()
	defer fake.withTxMutex.RUnlock()
	return len(fake.withTxArgsForCall)
}

func (fake *PersistentStoreProvider) WithTxCalls(stub func(context.Context) (store.Persistent, error)) {
	fake.withTxMutex.Lock()
	defer fake.withTxMutex.Unlock()
	fake.WithTxStub = stub
}

func (fake *PersistentStoreProvider) WithTxArgsForCall(i int) context.Context {
	fake.withTxMutex.RLock()
	defer fake.withTxMutex.RUnlock()
	argsForCall := fake.withTxArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PersistentStoreProvider) WithTxReturns(result1 store.Persistent, result2 error) {
	fake.withTxMutex.Lock()
	defer fake.withTxMutex.Unlock()
	fake.WithTxStub = nil
	fake.withTxReturns = struct {
		result1 store.Persistent
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) WithTxReturnsOnCall(i int, result1 store.Persistent, result2 error) {
	fake.withTxMutex.Lock()
	defer fake.withTxMutex.Unlock()
	fake.WithTxStub = nil
	if fake.withTxReturnsOnCall == nil {
		fake.withTxReturnsOnCall = make(map[int]struct {
			result1 store.Persistent
			result2 error
		})
	}
	fake.withTxReturnsOnCall[i] = struct {
		result1 store.Persistent
		result2 error
	}{result1, result2}
}

func (fake *PersistentStoreProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.accountCreateMutex.RLock()
	defer fake.accountCreateMutex.RUnlock()
	fake.accountGetByMutex.RLock()
	defer fake.accountGetByMutex.RUnlock()
	fake.commitTxMutex.RLock()
	defer fake.commitTxMutex.RUnlock()
	fake.rollbackTxMutex.RLock()
	defer fake.rollbackTxMutex.RUnlock()
	fake.withTxMutex.RLock()
	defer fake.withTxMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PersistentStoreProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ store.Persistent = new(PersistentStoreProvider)
