services:
  postgres:
    build:
      context: dev/database/
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 2s
      retries: 5

  api:
    build:
      context: ./
      dockerfile: cmd/service/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - dev/local.env
    restart: on-failure
    depends_on:
      - postgres

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
