# For debuging purposes, in this case integrated with VS Code debugging
services:
  postgres:
    build:
      context: dev/database/
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 2s
      retries: 5
