definitions:
  service.loginResponse:
    properties:
      created:
        type: string
      email:
        type: string
      id:
        type: string
      token:
        type: string
      updated:
        type: string
    type: object
  service.notificationRequest:
    properties:
      message:
        type: string
    type: object
  types.AuthCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AuthCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.loginResponse'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AuthCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Register
      tags:
      - Auth
  /user/:id/notifications:
    post:
      consumes:
      - application/json
      description: Sends a notification to user id trough websocket
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.notificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: SendNotificationToUser
      tags:
      - Notifications
  /ws/user/notifications:
    get:
      description: Connect to a WebSocket to receive notifications
      parameters:
      - description: X-Authorization
        in: header
        name: Cookie
        required: true
        type: string
      responses: {}
      summary: NotificationsWebSocket
      tags:
      - Notifications
swagger: "2.0"
